[package]
name = "rust_intl"
version.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
edition.workspace = true

[lib]
name = "rust_intl"

[dependencies]
rust_intl_macros = { workspace = true }
icu_plurals = { version = "2.2", features = ["compiled_data"] }
icu_decimal = { version = "2.2", features = ["compiled_data"] }
fixed_decimal = "0.7"
icu_locale_core = "2.2"
